INSERT INTO periodico.articulo (autor, categoria, fecha, texto, titulo) VALUES ('EuropaPress', 'Eskerraldea', '2022/05/16', 'BBK Karpin Fauna, ubicado en Karrantza, inaugura un nuevo reptilario con reptiles abandonados o que han sido objeto de tráfico de ilegal, como serpientes, lagartos, varanos, tortugas o caimanes.', 'BBK Karpin Fauna inaugura un nuevo reptilario con reptiles abandonados o de tráfico de ilegal');
INSERT INTO periodico.articulo (autor, categoria, fecha, texto, titulo) VALUES ('Pablo Viñas', 'Salud', '2022/05/16', 'Euskadi registró 1.666 muertes debido al covid-19 en 2021, frente a las 3.096 de 2020. Las defunciones por coronavirus fueron 261 en el cuarto trimestre del pasado año, un 73% menos que en el mismo periodo de 2020, según datos elaborados por Eustat.', 'Euskadi registró 1.666 muertes por covid en 2021, frente a las 3.096 de 2020');
INSERT INTO periodico.articulo (autor, categoria, fecha, texto, titulo) VALUES ('Pako Ruiz', 'Athletic', '2022/05/10', 'Si quieres taza, toma taza y media. El Athletic se ha ridiculizado así mismo en Los Cármenes en un encuentro infame del colectivo de un Marcelino que tampoco ha estado al nivel que pedía el compromiso. El conjunto rojiblanco ha jugado a nada y ha depreciado su candidatura a atrapar una de las dos plazas europeas que restan por repartir después de sucumbir en un partido que ha proyectado incluso momentos de auténtica comedia, lo que acentúa más el monumental fiasco de un Athletic al que solo le queda rezar a la amatxu de Begoña para retornar a una competición continental. Si Villarreal y Real Sociedad lograran la victoria en los respectivos duelos que afrontan el jueves, ante el Rayo en Vallecas y el Cádiz en Anoeta, los leones se despedirían prácticamente de sus ya pocas opciones, una historia que se repite en los últimos tiempos y que deja en mal lugar a los futbolistas y al entrenador, conscientes de la pobrísima imagen que han ofrecido en una cita trascendental para sus intereses ante un Granada que se les ha comido en intensidad y deseo. El conjunto del exleón Aitor Karanka se ha valido de un regalo de Dani García y el episodio cómico ha sido aún mayor en el descuento, con el gol anulado al colombiano Luis Suárez con Unai Simón en pleno retorno de su subida al área nazarí, el remate posterior al palo de Raúl García y, para rizar el rizo, un posible penaltito sobre Zarraga no señalado. Ver para creer. Se mire como se mire, un fracaso.', 'El Athletic se deprecia en Granada');


INSERT INTO periodico.opinion (contenido, email, fecha, nombre, articulo_id) VALUES ('Asi no hay forma de llegar a UEFA', 'rodriguez@gmail.com', '2022/05/11', 'Manu Rodriguez', '3');
INSERT INTO periodico.opinion (contenido, email, fecha, nombre, articulo_id) VALUES ('Lo del Covid es una farsa, menuda conspiracion. Todo es una PLANDEMIA...', 'nosvigilan@terra.es', '2022/05/16', 'No te lo digo', '2');
INSERT INTO periodico.opinion (contenido, email, fecha, nombre, articulo_id) VALUES ('Alguien sabe si se puede ir con niños? Cuanto cuesta la entrada?', 'papifeliz@yahoo.net', '2022/05/16', 'PapiGuay', '1');
INSERT INTO periodico.opinion (contenido, email, fecha, nombre, articulo_id) VALUES ('La culpa de todo es de Urrutia. Ya veras con las elecciones como espabilan algunos...', 'goraleones@athletic.eus', '2022/05/12', 'ZuriGorri', '3');
